{{- if and .Values.debezium.enabled .Values.debezium.connectUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terrier-connect.fullname" . }}-debezium-secrets
  labels:
    {{- include "terrier-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEBEZIUM_DB_USER: {{ .Values.debezium.secrets.dbUser | quote }}
  DEBEZIUM_DB_PASSWORD: {{ .Values.debezium.secrets.dbPassword | quote }}
{{- end }}
