apiVersion: v1
kind: Service
metadata:
  name: {{ include "terrier-connect.fullname" . }}-gateway
  labels:
    {{- include "terrier-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    {{- include "terrier-connect.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: 4000
