apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terrier-connect.fullname" . }}-app-secrets
  labels:
    {{- include "terrier-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | quote }}
