apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - managed-cert.yaml
  - ingress.yaml

configMapGenerator:
  - name: app-config
    literals:
      - DB_NAME=terrier-connect-prod
      - DB_USER=appuser
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DEBUG=0
      - ALLOWED_HOSTS=example.com,www.example.com
      - CLOUDSQL_INSTANCE=PROJECT_ID:REGION:INSTANCE_NAME
      - USE_GCS=1
      - GS_BUCKET_NAME=terrier-connect-media
      - GS_PROJECT_ID=PROJECT_ID
      - GS_QUERYSTRING_AUTH=false

secretGenerator:
  - name: app-secrets
    literals:
      - DB_PASSWORD=CHANGE_ME
      - SECRET_KEY=CHANGE_ME

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
  - patch-server-cloudsql.yaml
  - patch-server-replicas.yaml
  - patch-client-replicas.yaml
  - patch-server-serviceaccount.yaml
