apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server-serviceaccount.yaml
  - server-deployment.yaml
  - server-service.yaml
  - consumer-outbox-relay-deployment.yaml
  - consumer-feed-deployment.yaml
  - consumer-notification-deployment.yaml
  - consumer-like-counter-deployment.yaml
  - consumer-search-indexer-deployment.yaml
  - client-deployment.yaml
  - client-service.yaml
